version: '3.8'

volumes:
  HNG-nginx-logs:
  nextcloud-data:

services:
  nextcloud:
    image: kefaslungu/hng-nextcloud
    restart: always
    volumes:
      - nextcloud-data:/var/www/html
      - HNG-nginx-logs:/var/log/nginx:ro
    networks:
      - hng-net

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - HNG-nginx-logs:/var/log/nginx
    depends_on:
      - nextcloud
    networks:
      - hng-net

  detector:
    build: ./detector
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - HNG-nginx-logs:/var/log/nginx:ro
      - ./detector/config.yaml:/app/config.yaml
    environment:
      - PYTHONUNBUFFERED=1

networks:
  hng-net:
    driver: bridge
